AWSTemplateFormatVersion: 2010-09-09
Description: lms application
# Resources section
Resources:
#lms VPC
  lmsVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
       - Key: Name
         Value: lmsvpc
#lmswebsubnet
  lmswebSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref lmsVPC
      CidrBlock: 10.0.0.0/20
      AvailabilityZone: us-west-2a
      Tags:
       - Key: Name
         Value: websubnet         
#lmsappsubnet
  lmsappSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref lmsVPC
      CidrBlock: 10.0.16.0/20
      AvailabilityZone: us-west-2a
      Tags:
       - Key: Name
         Value: appsubnet 
#lmsdbsubnet
  lmsdbSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref lmsVPC
      CidrBlock: 10.0.32.0/20
      AvailabilityZone: us-west-2a
      Tags:
       - Key: Name
         Value: dbsubnet    
#lmsinternetgateway
  lmsInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
       - Key: Name
         Value: InternetGateway    
#lms AttachInternetGateway                   
  lmsAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: lmsVPC
      InternetGatewayId:
        Ref: lmsInternetGateway
#lmspublicrouttable 
  lmspublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: lmsVPC
      Tags:
       - Key: Name
         Value: public RT  
#lmsappSubnetRouteTableAssociation
  lmsappSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: lmsappSubnet
      RouteTableId:
        Ref: lmspublicRouteTable
#lmswebSubnetRouteTableAssociation
  lmswebSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: lmswebSubnet
      RouteTableId:
        Ref: lmspublicRouteTable        

        
