AWSTemplateFormatVersion: 2010-09-09
Description: lms application
# Resources section
Resources:
#lms VPC
  lmsVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
       - Key: Name
         Value: lmsvpc
#lmswebsubnet
  lmswebSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref lmsVPC
      CidrBlock: 10.0.0.0/20
      AvailabilityZone: us-west-2a
      Tags:
       - Key: Name
         Value: websubnet         